"""Bundled Next.js dashboard static export served by `dm-secure ui`.

The files in this directory are generated by `next build` (output: export) and
copied here so the wheel can ship a self-contained, zero-runtime-dependency
dashboard. They are not Python sources.
